
spring:
  datasource:
    url: jdbc:sqlserver://<servername>:<portnumber>;databaseName=<database name>;encrypt=false;trustServerCertificate=true
    username: <username>
    password: <password>
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
      naming-strategy: com.sriram_api_assignment.Restaurent_Api_Group_Assignment.CustomPhysicalNamingStrategy
    show-sql: true
